### ISSUE TITLE
pleASE

### ISSUE THREAD

**Issue by DimonYoing** [Wertzui123/SignIt#9]
Please make a message in the chat "You have successfully signed the item in hand"

**Comment by Wertzui123** [comment]
There is already one?

**Comment by DimonYoing** [comment]
so you did not add this in the latest version, I signed the item but nothing was written in the chat

**Comment by DimonYoing** [comment]
Here make a message in the chat that signed the item

**Comment by Wertzui123** [comment]
You're right, I can confirm this bug.
It has been fixed in edd36ee.
